"""Verify the real dashboard against the built API. Requires Playwright for Python."""
from pathlib import Path
import tempfile
from playwright.sync_api import sync_playwright, expect
from test_support import Server, DIAGNOSIS_KEY, LEARNING_KEY

artifacts = Path("test-artifacts")
artifacts.mkdir(exist_ok=True)
errors = []
with tempfile.TemporaryDirectory(prefix="secure-intelligence-browser-") as directory:
    with Server(directory) as server, sync_playwright() as playwright:
        browser = playwright.chromium.launch()
        context = browser.new_context(viewport={"width": 1440, "height": 1000})
        page = context.new_page()
        page.on("pageerror", lambda error: errors.append(str(error)))
        page.goto(server.url)
        expect(page.get_by_role("heading", name="Diagnosis", exact=True)).to_be_visible()
        page.get_by_label("API key", exact=True).fill(LEARNING_KEY)
        page.get_by_role("button", name="Connect", exact=True).click()
        expect(page.locator("#access-status")).to_have_text("Reviewer access")
        assert page.locator("#api-key").input_value() == ""
        page.get_by_role("button", name="Load example", exact=True).click()
        page.get_by_role("button", name="Run diagnosis", exact=True).click()
        expect(page.get_by_role("heading", name="3 rule findings")).to_be_visible()
        page.get_by_role("button", name="Knowledge", exact=True).click()
        expect(page.get_by_role("heading", name="No published guides yet")).to_be_visible()
        page.get_by_text("Publish a reviewed guide", exact=True).click()
        page.get_by_role("button", name="Load example guide").click()
        malicious_title = "Approved guide <script>window.__xss=true</script>"
        page.locator("#doc-title").fill(malicious_title)
        page.locator("#doc-approved").check()
        page.get_by_role("button", name="Publish guide", exact=True).click()
        expect(page.locator("#documents-list")).to_contain_text(malicious_title)
        assert page.evaluate("window.__xss === undefined")
        page.locator("#search-query").fill("BOM systemization")
        page.get_by_role("button", name="Search", exact=True).click()
        expect(page.locator("#search-results")).to_contain_text("Matched terms:")
        page.get_by_role("button", name="Diagnosis", exact=True).click()
        page.get_by_role("button", name="Run diagnosis", exact=True).click()
        expect(page.locator("#diagnostic-results")).to_contain_text(malicious_title)
        page.locator("#proposal-cause").fill("Browser verified cause")
        page.locator("#proposal-resolution").fill("Run approved validation")
        page.get_by_role("button", name="Submit for review", exact=True).click()
        expect(page.locator("#notice")).to_contain_text("Case queued for review")
        page.get_by_role("button", name="Learning reviews", exact=True).click()
        expect(page.locator("#reviews-list")).to_contain_text("Browser verified cause")
        page.get_by_role("button", name="Approve case", exact=True).click()
        expect(page.locator("#reviews-list .review-status")).to_have_text("Pending")
        page.get_by_label("I verified the cause and resolution and approve this case for learning.").check()
        page.get_by_role("button", name="Approve case", exact=True).click()
        expect(page.locator("#notice")).to_contain_text("Case approved and published")
        page.get_by_role("button", name="Approved cases", exact=True).click()
        expect(page.locator("#cases-list")).to_contain_text("Browser verified cause")
        page.get_by_label("I verified this outcome for the incident. Reusing an ID corrects the existing record.").check()
        page.get_by_role("button", name="Record outcome", exact=True).click()
        expect(page.locator("#cases-list")).to_contain_text("1 verified resolved")
        page.get_by_label("Resolution outcome").select_option("false")
        page.get_by_label("I verified this outcome for the incident. Reusing an ID corrects the existing record.").check()
        page.get_by_role("button", name="Record outcome", exact=True).click()
        expect(page.locator("#cases-list")).to_contain_text("0 verified resolved · 1 verified unresolved")
        page.get_by_role("button", name="Inspect signals", exact=True).click()
        expect(page.locator("#cases-list table")).to_contain_text("bomItemCount")
        page.get_by_role("button", name="Diagnosis", exact=True).click()
        page.get_by_role("button", name="Run diagnosis", exact=True).click()
        expect(page.locator("#diagnostic-results")).to_contain_text("Browser verified cause")
        expect(page.locator("#diagnostic-results")).to_contain_text("Stored")
        page.locator("#proposal-cause").fill("Browser rejected cause")
        page.locator("#proposal-resolution").fill("Unverified proposed resolution")
        page.get_by_role("button", name="Submit for review", exact=True).click()
        expect(page.locator("#notice")).to_contain_text("Case queued for review")
        page.get_by_role("button", name="Learning reviews", exact=True).click()
        page.get_by_label("Rejection reason").select_option("IncorrectCause")
        page.get_by_role("button", name="Reject", exact=True).click()
        expect(page.locator("#notice")).to_contain_text("Proposal rejected")
        page.locator("#review-filter").select_option("Rejected")
        expect(page.locator("#reviews-list")).to_contain_text("IncorrectCause")
        page.get_by_role("button", name="Diagnosis", exact=True).click()
        page.screenshot(path=str(artifacts / "dashboard-desktop.png"), full_page=True)
        assert page.evaluate("document.documentElement.scrollWidth <= window.innerWidth")
        assert page.evaluate("localStorage.length === 0 && sessionStorage.length === 0")
        mobile = context.new_page()
        mobile.set_viewport_size({"width": 390, "height": 844})
        mobile.on("pageerror", lambda error: errors.append(str(error)))
        mobile.goto(server.url)
        mobile.get_by_label("API key", exact=True).fill(LEARNING_KEY)
        mobile.get_by_role("button", name="Connect", exact=True).click()
        expect(mobile.locator("#access-status")).to_have_text("Reviewer access")
        mobile.get_by_role("button", name="Knowledge", exact=True).click()
        mobile.locator("#search-query").fill("BOM")
        mobile.get_by_role("button", name="Search", exact=True).click()
        expect(mobile.locator("#search-results")).to_contain_text("Matched terms:")
        mobile.screenshot(path=str(artifacts / "dashboard-mobile.png"), full_page=True)
        assert mobile.evaluate("document.documentElement.scrollWidth <= window.innerWidth")
        mobile.get_by_role("button", name="Disconnect", exact=True).click()
        expect(mobile.locator("#access-status")).to_have_text("Not connected")
        expect(mobile.locator("#search-results")).to_be_empty()
        mobile.get_by_label("API key", exact=True).fill(DIAGNOSIS_KEY)
        mobile.get_by_role("button", name="Connect", exact=True).click()
        expect(mobile.locator("#access-status")).to_have_text("Caller access")
        expect(mobile.locator(".publish-panel")).to_be_hidden()
        mobile.get_by_role("button", name="Learning reviews", exact=True).click()
        expect(mobile.get_by_role("heading", name="Reviewer access required")).to_be_visible()
        mobile.reload()
        expect(mobile.locator("#access-status")).to_have_text("Not connected")
        assert not errors, errors
        browser.close()
print("PASS real browser workflow: diagnosis, guide publication/search, proposal approval/rejection, outcomes, escaped content, mobile layout and session clearing")
